### ISSUE TITLE
The fullnode does not connect to the validator and is not synchronized when installing nodes on different servers (testnet).

### ISSUE THREAD

**Issue by infiniti8** [aptos-labs/aptos-core#1001]
# 🐛 Bug

Hi, team!

Today I installed the validator and the fullnode on different servers with different public addresses from the github source. I generated all the keys, including using the private key for the validator, I generated the peer ID for the validator using Aptos CLI, like this:

`aptos key extract-peer --private-key-file private-key.txt \
                                      --output-file peer-info.yaml"`

The validator successfully synchronizes with the network. But the fullnode is not synced. My configs look like this:

**validator.yaml**
```
base:
  role: "validator"
  data_dir: "/root/AptosTestnet/data"
  waypoint:
    from_file: "/root/AptosTestnet/waypoint.txt"

consensus:
  safety_rules:
    service:
      type: "local"
    backend:
      type: "on_disk_storage"
      path: /root/AptosTestnet/data/secure-data.json
      namespace: ~
    initial_safety_rules_config:
      from_file:
        waypoint:
          from_file: /root/AptosTestnet/waypoint.txt
        identity_blob_path: /root/AptosTestnet/validator-identity.yaml

execution:
  genesis_file_location: "/root/AptosTestnet/genesis.blob"
  concurrency_level: 4

validator_network:
  discovery_method: "onchain"
  mutual_authentication: true
  identity:
    type: "from_file"
    path: /root/AptosTestnet/validator-identity.yaml

full_node_networks:
- network_id:
    private: "vfn"
  listen_address: "/ip4/0.0.0.0/tcp/6181"
  identity:
    type: "from_config"
    key: "901f543cdc23e83d262de1f879*******622493db9a73c976def9dcda2a7a97b"
    peer_id: "84a8d9c0c45bb0a7071ca5a849055c7d7c97a8a13156542f0853d5a2706e377d"

api:
  enabled: true
  address: "0.0.0.0:8080"
```
**fullnode.yaml**
```
base:
  role: "full_node"
  data_dir: "/root/AptosTestnet/data"
  waypoint:
    from_file: "/root/AptosTestnet/waypoint.txt"

execution:
  genesis_file_location: "/root/AptosTestnet/genesis.blob"

full_node_networks:
- network_id:
    private: "vfn"
  listen_address: "/ip4/0.0.0.0/tcp/6181"
  seeds:
    84a8d9c0c45bb0a7071ca5a849055c7d7c97a8a13156542f0853d5a2706e377d:
        addresses:
        - "/ip4/173.249.60.152/tcp/6181/ln-noise-ik/84a8d9c0c45bb0a7071ca5a849055c7d7c97a8a13156542f0853d5a2706e377d/ln-handshake/0"
        role: "Validator"

- network_id: "public"
  discovery_method: "onchain"
  listen_address: "/ip4/0.0.0.0/tcp/6182"
  max_inbound_connections: 100
  identity:
    type: "from_file"
    path: "/root/AptosTestnet/validator-full-node-identity.yaml"

api:
  enabled: true
  address: "0.0.0.0:8080"
```

There is the following error in the fullnode logs:
![image](https://user-images.githubusercontent.com/80079858/168447528-66f9effd-4bde-41ad-99e9-6cee42ce7667.png)

When installing both nodes on the same server via Docker, the fullnode is successfully synchronized. I think this is because the validator and the fullnode are on the same local network 172.16. But I think that installing both nodes on the same server is unsecurity and wrong. In this connection, I decided to install nodes through sources on different servers.

Perhaps the reason that the fullnode is not connecting to the validator is due to the configuration of the validator? I mean consensus settings. By default, the service type is "local", I tried to use the "process" service type with the server address, for example, the validator address is 0.0.0.0 and port 6181, but this did not solve the synchronization problem. I have all the necessary ports open, I checked through nc.

Or is it just because the testnet hasn't launched yet? =)
