### ISSUE TITLE
[Bug] Build Failure

### ISSUE THREAD

**Issue by StephenMal** [aptos-labs/aptos-core#10293]
# 🐛 Bug

Failure to build as the only dependency

## To reproduce

Cargo.toml:
```toml
[package]
name = "aptos-sdk-as-dependency"
version = "0.0.1"
edition = "2021"

[dependencies]
aptos-sdk = { git = "https://github.com/aptos-labs/aptos-core", branch = "devnet"}

[patch.crates-io]
merlin = { git = "https://github.com/aptos-labs/merlin" }
```

**Stack trace/error message**
```
error[E0599]: no method named `disable_lifo_slot` found for mutable reference `&mut tokio::runtime::Builder` in the current scope
  --> /home/stphn/.cargo/git/checkouts/aptos-core-8f3268fcf79e1f38/36eddf6/crates/aptos-runtimes/src/lib.rs:45:10
   |
39 | /     builder
40 | |         .thread_name_fn(move || {
41 | |             let id = atomic_id.fetch_add(1, Ordering::SeqCst);
42 | |             format!("{}-{}", thread_name_clone, id)
43 | |         })
44 | |         .on_thread_start(on_thread_start)
45 | |         .disable_lifo_slot()
   | |         -^^^^^^^^^^^^^^^^^ private field, not a method
   | |_________|
```

## Expected Behavior

Successful build

## System information

Test 1:
rustc 1.72.0 (5680fa18f 2023-08-23) & rustc 1.72.1 (d5c2e9c34 2023-09-13)
cargo 1.72.0 (103a7ff2e 2023-08-15) & cargo 1.72.1 (103a7ff2e 2023-08-15)
Kubuntu 23.04
Aptos Core 0.1.0
