### ISSUE TITLE
[Bug] [Package System] Dependency version not checked

### ISSUE THREAD

**Issue by fEst1ck** [aptos-labs/aptos-core#13315]
# 🐛 Bug

The current package system allows us to specify the version of a dependency as in

```toml
[dependencies]
P2 = { local = "../p2", version = "2.0.0" }
```

but the version is not checked. Suppose we have in the manifest of package P2

```toml
[package]
name = "P2"
version = "1.0.0"
```

no error is raised. This version key is also not specified in the [move book](https://aptos.dev/move/book/packages).

## Expected Behavior

If the version declared in the dependency package manifest doesn't match the one given in the [dependency] section of the importing package, raise an error.
