### ISSUE TITLE
[Bug] [aptos-cli] dev-dependency is only used when dependency is commented out in dev mode

### ISSUE THREAD

**Issue by 0xaptosj** [aptos-labs/aptos-core#14177]
# 🐛 Bug

To report a security issue, please email security@aptoslabs.com.

I'm trying to mock ANS with a local version. the expected behavior is when I run `aptos move test` with `--dev`, it should automatically use `dev-dependencies` version of ANS. But it is not, it only uses `dev-dependencies` version of ANS after I commented out `router` in `dependencies`, is this expected?

## To reproduce

**Code snippet to reproduce**
Here's my `Move.toml`
```toml
[package]
name = "fungible_asset_launchpad"
version = "1.0.0"
authors = []

[addresses]
launchpad_addr = '_'
initial_creator_addr = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}
// I need to comment this out to use dev-dependency, is this expected?
router = { git = "https://github.com/aptos-labs/aptos-names-contracts.git", rev = "main", subdir = "router"}

[dev-dependencies]
router = { local = "../../aptos-names-contracts/router" }
```

Here's how I run unit test
```sh
PUBLISHER_ADDR="0x100"
ANS_ADDR="0x101"

aptos move test \
  --package-dir $MOVE_DIR \
  --named-addresses "launchpad_addr=$PUBLISHER_ADDR, initial_creator_addr=$PUBLISHER_ADDR, aptos_names=$ANS_ADDR, aptos_names_admin=$ANS_ADDR, aptos_names_funds=$ANS_ADDR, router_signer=$ANS_ADDR, aptos_names_v2_1=$ANS_ADDR, router=$ANS_ADDR" \
  --dev
```

My unit test
```move
#[test_only]
module launchpad_addr::play_with_ans {
    #[test_only]
    use router::router;

    #[test(
        aptos_framework = @0x1,
        sender = @launchpad_addr,
    )]
    fun test_happy_path(
        aptos_framework: &signer,
        sender: &signer,
    ) {
        router::set_mode(sender, 10);
    }
}
```

**Stack trace/error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- Aptos Core Version
- Rust Version
- Computer OS
