### ISSUE TITLE
[Bug] Getting error when using aptos-framework main branch

### ISSUE THREAD

**Issue by lumos42** [aptos-labs/aptos-core#14240]
# 🐛 Bug

I am getting an error when I try to run tests in my code while using aptos-framework main branch.
```toml
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "7b0872a61ecb3cf782e4bdabc091c171b78efa29" }  ==> this works
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }  ==> this doesn't work

```

## To reproduce

Since the error originates from smart_table module, I was able to reproduce this error in the [package-manager move example](https://github.com/aptos-labs/aptos-core/tree/main/aptos-move/move-examples/package_manager).

1. Replace the aptos framework dependency in Move.toml to use git
```
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }
```
2. Run tests:
```
aptos move test --named-addresses deployer=0xcafe,package=0xcafe
```
It fails with the following error message:

**Stack trace/error message**
```
Failures in 0xcafe::package_manager_tests:

┌── test_can_set_and_get_address ──────
│ error[E11001]: test failure
│    ┌─ /Users/lumos/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/../aptos-stdlib/../move-stdlib/sources/bcs.move:12:23
│    │
│ 12 │     native public fun serialized_size<MoveValue>(v: &MoveValue): u64;
│    │                       ^^^^^^^^^^^^^^^
│    │                       │
│    │                       INTERNAL TEST ERROR: Unexpected Verification Error
│ Test was not expected to error, but it gave a MISSING_DEPENDENCY (code 1021) error with error message: "Missing Native Function `serialized_size`". Error originating in the module 0000000000000000000000000000000000000000000000000000000000000001::bcs rooted here
│    │                       In this function in 0x1::bcs
│
│
│ stack trace
│ 	smart_table::add(/Users/lumos/.move/https___github_com_aptos-labs_aptos-core_git_main/aptos-move/framework/aptos-framework/../aptos-stdlib/sources/data_structures/smart_table.move:145)
│ 	package_manager::add_address(/Users/lumos/projects/moar/aptos-core/aptos-move/move-examples/package_manager/sources/package_manager.move:54)
│ 	package_manager_tests::test_can_set_and_get_address(/Users/lumos/projects/moar/aptos-core/aptos-move/move-examples/package_manager/sources/tests/package_manager_tests.move:17)
│
└──────────────────

Test result: FAILED. Total tests: 2; passed: 1; failed: 1
{
  "Error": "Move unit tests failed"
}
```

I also got the same error when running tests on my code base using aptos framework main branch. I was able to make it work using a slightly older version(7b0872a61ecb3cf782e4bdabc091c171b78efa29) ps aptos-core instead of mai.

## Expected Behavior

The tests should work with aptos framework main branch.

## System information

**Please complete the following information:**
- Aptos Core Version - Aptos CLI version `aptos 3.5.1`, aptos-core version 06900559ea5f03b380b1637b861cdab34501ed2d 
- Rust Version - rustc 1.78.0 (9b00956e5 2024-04-29)
- Computer OS - Mac OS 14.5 (23F79)

## Additional context

Let me know if any further details are required.
