### ISSUE TITLE
[Bug] local gas simulation fails when publishing module with event emitted in `init_module`

### ISSUE THREAD

**Issue by meng-xu-cs** [aptos-labs/aptos-core#14466]
# 🐛 Bug

As described in the title.

To further illustrate:

Launch local testnet in one terminal session
```bash
aptos node run-local-testnet --with-faucet --force-restart
```

Prepare a demo account
```bash
aptos init --network local --profile demo --private-key <some-key> --skip-faucet --assume-yes
aptos account fund-with-faucet --profile demo --account demo --amount 100000
```

and then try to publish a Move package with the following criteria:
- the Move package has an `init_module` function
- the `init_module` function emit an event
- publish the package with `aptos move publish` with no `--gas-unit-price` or `--max-gas` specified
```bash
aptos move publish --profile demo --sender-account demo --package-dir <path-to-dir-with-Move.toml>
```

The module publishing will fail with:
```json
{
    "Error": "API error: API error Error(InternalError): Failed to convert transaction data from storage: Module ModuleId { address: 26977f29f5a80a53c3153613555b05146a5e100c4438c647cf95f452b2e0f96f, name: Identifier(\"demo\") } can't be found"
}
```

However, if you specify both `--gas-unit-price` and `--max-gas` during `aptos move publish`, the transaction is successful.

## To reproduce

See the steps above. The Move.toml and Move module is shown below

**Code snippet to reproduce**

- Move.toml
```toml
[package]
name = "Demo"
version = "1.0.0"
upgrade_policy = "compatible"
authors = []

[addresses]
demo = '_'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "main" }
```

- sources/demo.move
```move
module demo::demo {
    use aptos_framework::event;

    #[event]
    struct MyEvent has store, drop {
        value: u64,
    }

    fun init_module(_sender: &signer) {
        event::emit(MyEvent { value: 42 });
    }
}
```

**Stack trace/error message**
```
// Paste the output here
```

## Expected Behavior

See above

## System information

**Please complete the following information:**
- Aptos Core Version: `main` as of commit `d231082fb611f84a17a43d7b961943245aade35c` on Aug 29
- Rust Version: 1.78.0
- Computer OS: MacOS 14.5
