### ISSUE TITLE
Localnet terminates when enabling the storage sharding

### ISSUE THREAD

**Issue by junkil-park** [aptos-labs/aptos-core#14759]
The localnet unexpectedly terminates if we're building and running a localnet from the main branch with the following flags enabled in the node config:
```
indexer_db_config:
    enable_event: true
    enable_statekeys: true
    enable_transaction: true

storage:
    rocksdb_configs:
        enable_storage_sharding: true
```

The localnet is terminating with the following error:
```
panicked at ecosystem/indexer-grpc/indexer-grpc-fullnode/src/stream_coordinator.rs:429:21:
[Indexer Fullnode] Could not convert txn 0 from OnChainTransactions: Table info reader is not available"""
```
