### ISSUE TITLE
[Feature Request] `pre-commit` support for CLI

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#14789]
# Todo

cc @banool @chen-robert @xbtmatt @crbl69 @wrwg 

- [ ] Add `pre-commit` hook for `aptos`
- [ ] Add support for testing (e.g. assert all tests pass)
- [ ] Add support for coverage (e.g. assert a certain percentage)
- [ ] Add support for formatting (related https://github.com/movebit/movefmt/issues/39)
- [ ] Auto-discovery for multiple packages in a repo
- [ ] Ability to exclude certain packages

## Motivation/pitch

This tooling will make it easier for ecosystem to develop safe code

## Additional context

Something like the config I currently have for Rust,which can do `fmt`, `cargo check`, and `clippy` all from the same `pre-commit` hook:

```yaml
-
  hooks:
  -
    args:
    - '--manifest-path'
    - 'src/rust/Cargo.toml'
    - '-p'
    - 'allowlister3000'
    - 'broker'
    - '--'
    id: 'fmt'
  -
    args:
    - '--manifest-path'
    - 'src/rust/Cargo.toml'
    - '--'
    id: 'cargo-check'
  -
    args:
    - '--manifest-path'
    - 'src/rust/Cargo.toml'
    - '--'
    - '--deny'
    - 'clippy::all'
    id: 'clippy'
  repo: 'https://github.com/doublify/pre-commit-rust'
  rev: 'v1.0'
```
