### ISSUE TITLE
[Bug]: Named Address Resolution Priority

### ISSUE THREAD

**Issue by mshakeg** [aptos-labs/aptos-core#15405]
# 🐛 Bug

The Aptos CLI does not prioritize address literals specified in a project's `Move.toml` when resolving named addresses from dependencies. Instead, it requires these addresses to be specified either in the dependency's Move.toml or via the `--named-addresses` flag, leading to unnecessarily complex deployment workflows.

## To reproduce

**Code snippet to reproduce**

```toml
# My Project's Move.toml
[package]
name = "MyProject"
version = "1.0.0"

[addresses]
resource_pm = "0x123"  # This should override dependency's address

[dependencies.AavePool]
git = "https://github.com/aave/aptos-aave-v3.git"
rev = "main"
subdir = "aave-core"
```

**Stack trace/error message**
```
error[E03001]: address with no value
   │
34 │         let config = borrow_global<Config>(@resource_pm);
   │                                            ^^^^^^^^^^^ address 'resource_pm' is not assigned a value. Try assigning it a value when calling the compiler
```

## Expected Behavior
When compiling a Move project:
1. The Aptos CLI should first check for named addresses in the root project's Move.toml
2. If not found, fall back to checking the dependency's `Move.toml`
3. Finally, consider any addresses specified via `--named-addresses` flag

This follows the principle of configuration inheritance where local project settings should be able to override dependency settings.

## System information

- aptos 4.4.0

## Additional context

Current workarounds include:
1. Using Aptos CLI profiles and passing addresses via `--named-addresses`
2. Maintaining complex Makefiles to manage address resolution
3. Modifying dependency `Move.toml` files directly

These workarounds make dependency management more complex than necessary and violate the principle of being able to configure dependencies from the root project.

This behavior particularly impacts projects that want to:
- Use different address configurations for testing vs production
- Fork and modify existing Move packages
- Maintain consistent address configurations across multiple environments
