### ISSUE TITLE
[Bug][compiler-v2] Randomness errors out for `fun init_module` even though it is private

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#15436]
@brmataptos @fEst1ck @georgemitenkov @gregnazario  @rahxephon89 @runtian-zhou @vineethk @wrwg

# General 

When I try and use randomness during `init_module` to initialize state using onchain randomness, the compiler errors out with:

```sh
error: only private or public(friend) entry functions can have #[randomness] attribute
  ┌─ /the_files_are_in_the_computer/init_random/sources/init_random.move:9:9
  │
9 │     fun init_module(publisher: &signer) {
  │ 
```

# To reproduce

```move
module publisher::init_random {
    use aptos_framework::randomness::Self;

    struct RandomNumber has key {
        number: u64,
    }

    #[randomness]
    fun init_module(publisher: &signer) {
        move_to(publisher, RandomNumber { number: randomness::u64_integer() });
    }

}
```

```toml
[package]
name = "InitRandom"
version = "1.0.0"

[addresses]
publisher = "_"

[dev-addresses]
publisher = "0xaaa"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"
```
