### ISSUE TITLE
[Bug] indexer-grpc-fullnode convert error

### ISSUE THREAD

**Issue by bbaktaeho** [aptos-labs/aptos-core#15439]
# 🐛 Bug

## System information

**Please complete the following information:**
- Aptos Core Version: v1.23.2
- Rust Version
- Computer OS

## Additional context

- fullnode.yaml
```
...
storage:
 enable_indexer: true
    # This is to avoid the node being pruned
 storage_pruner_config:
  ledger_pruner_config:
   enable: false

indexer_grpc:
  enabled: true
  address: 0.0.0.0:50051
  processor_task_count: 10
  processor_batch_size: 100
  output_batch_size: 100
...
```
I ran fullnode and tested grpc calls.
```
grpcurl  -max-msg-sz 100 -d '{ "starting_version": 1993304278 }' -import-path protos/proto  -proto aptos/internal/fullnode/v1/fullnode_data.proto  -plaintext <ip>:50051 aptos.internal.fullnode.v1.FullnodeData/GetTransactionsFromNode
```
The response is:
```
{
  "status": {
    "type": "STATUS_TYPE_INIT",
    "startVersion": "1993304278"
  },
  "chainId": 1
}
ERROR:
  Code: Unavailable
  Message: error reading from server: EOF
```

After checking the aptos-core log, a panic occurred at **ecosystem/indexer-grpc/indexer-grpc-fullnode/src/convert.rs:394**.
The cause was `write_table_item.data` was `None`.
