### ISSUE TITLE
[Feature Request]: Add network-specific named addresses configuration for Move packages

### ISSUE THREAD

**Issue by mshakeg** [aptos-labs/aptos-core#15938]
# 🚀 Feature Request

Add ability to specify named addresses per network via a configuration file, making it easier to manage deployments across different networks (testnet, mainnet, etc.)

## Motivation

Currently, developers managing Move packages that need to be deployed to multiple networks (testnet, mainnet, etc.) face challenges with managing network-specific addresses. The current solutions are either:

1. Maintain separate long `--named-addresses` CLI strings for each network
2. Comment/uncomment different address configurations in Move.toml when switching networks

Both approaches are error-prone and create friction in the development workflow, especially when managing multiple packages or working in a team.

## Pitch

**Describe the solution you'd like**
Add support for a network configuration file (e.g., `networks.toml`) that defines named addresses for different networks:

```toml
[local]
some_address = "0x1"
some_other_address = "0x2"
another_address = "0x3"

[aptos-testnet]
some_address = "0x123..."
some_other_address = "0x456..."
another_address = "0x789..."

[movement-mainnet]
some_address = "0xabc..."
some_other_address = "0xdef..."
another_address = "0xghi..."


```

Then extend the CLI to support specifying the network as the value for `--named-addresses`:
```bash
aptos move compile --named-addresses movement-mainnet
```

This would:
1. Read the network configuration file
2. Use the addresses specified for the given network
3. Replace any `"_"` placeholders in `Move.toml` with the network-specific addresses

**Describe alternatives you've considered**

1. Extending `Move.toml` to support network-specific sections - decided against this to keep `Move.toml` focused on package configuration rather than deployment configuration
2. Using environment variables - less maintainable and harder to version control
3. Creating separate `Move.toml` files per network - increases maintenance overhead and potential for configuration drift

**Are you willing to open a pull request?**

Not at the moment

## Additional context

This feature would align with common practices in other blockchain development frameworks where network-specific configurations are managed through dedicated configuration files. It would significantly improve the developer experience when working with Move packages that need to be deployed across multiple networks.

The implementation could also include validation to ensure that:
- All named addresses required by `Move.toml` are present in the network configuration
- Network configurations are complete and well-formed
- Clear error messages when network configurations are missing or invalid

This would also resolve https://github.com/aptos-labs/aptos-core/issues/15405
