### ISSUE TITLE
[Feature Request]: Add Address Visibility Control and Smart Resolution for Move Package Dependencies

### ISSUE THREAD

**Issue by mshakeg** [aptos-labs/aptos-core#15953]
# 🚀 Feature Request
Enhance Move package dependency management by introducing address visibility control and smart resolution, reducing configuration burden while maintaining encapsulation.

## Motivation
**Is your feature request related to a problem? Please describe.**
Currently, when developing a Move package that depends on another package, developers must specify ALL `[addresses]` from the dependency's `Move.toml` where placeholders(i.e. `"_"`) are used, even if they only use the main publisher address. While dependency packages might expose additional public addresses for advanced use cases, developers who don't need these additional addresses are still forced to specify them.

For example, if **MyAptosPackage** uses **ThirdPartyPackage** and only interacts with the main `third_party_package` address (where the package is published), developers are still forced to specify:
- Other public addresses they don't use
- Internal addresses used only by ThirdPartyPackage modules

This:
- Increases configuration complexity
- Forces unnecessary address specifications
- Creates maintenance overhead
- Makes package integration more difficult than necessary

Related issues: #15949, #15938

## Pitch
**Describe the solution you'd like**
1. Enhanced Network Configuration with Address Scoping:
```toml
# ThirdPartyPackage/networks.toml
[aptos-mainnet]
# Primary package address (always public)
public.third_party_package = "0x123..."

# Optional public addresses for advanced use cases
public.additional_feature_addr = "0x234..."

# Internal addresses
internal.module_specific_addr = "0x456..."
internal.utility_addr = "0x789..."
```

2. Smart Address Resolution in Compiler:
- First Pass (Usage Analysis):
  - Scan dependent package code to identify which addresses are actually referenced
  - Create dependency graph showing direct and indirect address requirements

- Second Pass (Scoped Resolution):
  - For public addresses: only require specification if actually used in the dependent's code and if not already specified in the dependency's `networks.toml`(though allow the dependent to override those addresses if their own `networks.toml`)
  - For internal addresses: automatically resolve from dependency's `networks.toml`
  - Ignore unused addresses entirely

3. Visibility Control:
- Prevent dependent packages from referencing internal addresses of dependencies
- Allow flexible usage of public addresses based on actual needs
- Compiler enforces visibility boundaries

Example usage for minimal case:

```toml
# my-aptos-package/Move.toml (only using main package address)
[package]
name = "MyAptosPackage"

[dependencies]
ThirdPartyPackage = { ... }

[addresses]
# Only need to specify the main package address we use
third_party_package = "_"
```

Example usage for advanced case:
```toml
# advanced-package/Move.toml (using additional features)
[package]
name = "AdvancedPackage"


[dependencies]
ThirdPartyPackage = { ... }

[addresses]
third_party_package = "_"
additional_feature_addr = "_"  # Only required because we use it
```

**Describe alternatives you've considered**

N/A

**Are you willing to open a pull request?**

Not at the moment

## Additional context

This proposal builds on and complements the network configuration (#15938) and dependency management (#15949) feature requests, adding specific improvements for address visibility and resolution.

Implementation would require:
1. Extending the Move compiler to perform usage analysis
2. Adding visibility control to the compiler
3. Modifying address resolution logic
4. Updating error messages to be clear about visibility violations

This would significantly improve the developer experience by:
- Reducing configuration burden
- Maintaining proper encapsulation
- Making dependencies explicit
- Simplifying package integration
- Preserving flexibility when needed
