### ISSUE TITLE
pruning is not working

### ISSUE THREAD

**Issue by dev-dantealighieri** [aptos-labs/aptos-core#15975]
hi,

i have an aptos mainnet node, whichs size passed 5TB, i want to do data pruning

I have the following storage configuration for my node, the disk usage didn't even reduced 100MB after enabling pruning, whats the issue here, how to fix?

```yaml
storage:
  storage_pruner_config:
    ledger_pruner_config:
      enable: true
      prune_window: 500000000
      batch_size: 10000000
```

thanks, dante
