### ISSUE TITLE
[Feature Request] Automatically provide project address alias to Move code (in `aptos cli move ...`)

### ISSUE THREAD

**Issue by wrwg** [aptos-labs/aptos-core#2631]
# 🚀 Feature Request

Spelling out 32 byte addresses (or for that matter, 16 bytes) is a total mess for DevX and that is why the Move language introduced address aliases.

The aptos cli has a concept of a profile and we should allow that profile to define an address alias which is used for Move sources. A first simple version would perhaps have a hardwired `project_account=X` address alias where `X` is the address  in the `account` field of `config.yaml`. This alias would then be just forwarded to the lower level Move code via existing mechanisms. Then I can write my Move code as

```
module project_account::MyFancyStuff { ... }
```

... and this code can easily move to different addresses.

An extended version of this feature would allow one to configure the name used for the project account in the profile config:

```
profiles:
  local:
    account: dacc2900a65de3079e499f4b01ad8348a09a8a60f957d547d0301104a21cae3f
    account_alias: my_fancy_stuff 
```

@gregnazario  @davidiw @banool @jjleng
