### ISSUE TITLE
[Bug] aptos move init creating dependency with outdated name

### ISSUE THREAD

**Issue by borispovod** [aptos-labs/aptos-core#2795]
# 🐛 Bug

The name of Aptos framework dependency after initialization of package using `aptos move init` seems wrong for me, it's `AptosFramework`1, should be `aptos_framework`.

Aptos CLI version v0.2.3.

## To reproduce

```sh
mkdir test-aptos
cd test-aptos
aptos move init --name test
cat Move.toml
```

See Move.toml:

```toml
[package]
name = "test"
version = "0.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }

[addresses]
```
