### ISSUE TITLE
 "Error": "Unexpected error: missing field min_voting_threshold at line 2 column 9"

### ISSUE THREAD

**Issue by garysdevil** [aptos-labs/aptos-core#3127]
aptos CLI: 0.2.5  or 0.2.0

```bash
aptos genesis generate-genesis --local-repository-dir ~/testnet --output-dir ~/testnet
```
```log
{
  "Error": "Unexpected error: missing field min_voting_threshold at line 2 column 9"
}
```
- layout.yaml
```yaml
---
root_key: "F22409A93D1CD12D2FC92B5F8EB84CDCD24C348E32B3E7A720F3D2E288E63394"
users:
- "aptosbot"
chain_id: 40
min_stake: 0
max_stake: 100000
min_lockup_duration_secs: 0
max_lockup_duration_secs: 2592000
epoch_duration_secs: 86400
initial_lockup_timestamp: 1656615600
min_price_per_gas_unit: 1
allow_new_validators: true
```
