### ISSUE TITLE
[Bug] Unable to start local indexer on MBP M1

### ISSUE THREAD

**Issue by kiennd** [aptos-labs/aptos-core#4955]
# 🐛 Bug

I was following the guide [here](https://github.com/aptos-labs/aptos-core/blob/main/crates/indexer/README.md). However, I am getting the following error:

`zsh: bus error  RUSTFLAGS="--cfg tokio_unstable" cargo run --bin aptos-node --features  --   `
## To reproduce
I ran the following command:
```
RUSTFLAGS="--cfg tokio_unstable" cargo run --bin aptos-node --features "indexer"  -- --config ./fullnode.yaml
```
With config:
```
storage:
   enable_indexer: true

indexer:
   enabled: true
   postgres_uri: "postgres://postgres@localhost:5432/postgres"
   processor: "default_processor"
   check_chain_id: true
   emit_every: 500
```

## System information

**Please complete the following information:**
- Aptos Core Version : lastest code: 
```
https://github.com/aptos-labs/aptos-core/commit/25696fd266498d81d346fe86e01c330705a71465
```
- Rust Version : rustc 1.63.0 (4b91a6ea7 2022-08-08)
- Macbook Pro 2021 M1
