### ISSUE TITLE
The node config file could not be found! Ensure the given path is correct

### ISSUE THREAD

**Issue by KorayBarkin** [aptos-labs/aptos-core#5236]
Hello everyone, when I try to run Aptos node via Docker it gives me this error:

![Screen Shot 2022-10-24 at 11 34 48](https://user-images.githubusercontent.com/70101145/197483624-5b46a188-64e5-490f-a9d2-4f2d106f4dc1.png)

Although I did change the path in docker-compose.yaml file and fullnode.yaml is in the correct path but does not recognize it.

![Screen Shot 2022-10-24 at 11 35 34](https://user-images.githubusercontent.com/70101145/197483801-1923c8e5-c1a4-410f-9e8f-989c3f2d16e6.png)

File:

```
# This compose file defines an Aptos Fullnode deployment.
# Read the README.md files for instruction on how to install aptos-node

version: "3.8"
services:
  haproxy:
    image: haproxytech/haproxy-debian:2.2
    volumes:
      - type: bind
        source: ./haproxy-fullnode.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
      - type: bind
        source: ./blocked.ips
        target: /usr/local/etc/haproxy/blocked.ips
    networks:
      - shared
    expose:
      # Public fullnode access
      - 6182
      # REST API
      - 80
      # Fullnode metrics
      - 9101
      # Haproxy stats page
      - 9102
    ports:
      - "6182:6182"
      - "80:80"
      # Only expose these internally
      - "0.0.0.0:9101:9101"
      - "0.0.0.0:9102:9102"

  fullnode:
    image: "${VALIDATOR_IMAGE_REPO:-aptoslabs/validator}:${IMAGE_TAG:-testnet}"
    networks:
      shared:
    volumes:
      - type: volume
        source: aptos-fullnode
        target: /opt/aptos/data
      - type: bind
        source: ./fullnode.yaml
        target: /opt/aptos/etc/fullnode.yaml
      - type: bind
        source: ./genesis.blob
        target: /opt/aptos/genesis/genesis.blob
      - type: bind
        source: ./waypoint.txt
        target: /opt/aptos/genesis/waypoint.txt
      - type: bind
        source: ./validator-full-node-identity.yaml
        target: /opt/aptos/genesis/validator-full-node-identity.yaml
    command: ["/usr/local/bin/aptos-node", "-f", "/home/ubuntu/aptos/fullnode.yaml"]
    restart: unless-stopped
    expose:
      # Public fullnode access
      - 6182
      # REST API
      - 80
      # Validator metrics
      - 9101

networks:
  shared:
    name: "aptos-docker-compose-shared"
    ipam:
      config:
        - subnet: 172.16.1.0/24

volumes:
  aptos-fullnode:
    name: aptos-fullnode
```
