### ISSUE TITLE
[APT-12] panicked at 'Could not fetch 500 transactions after 3 retries, starting at 515500

### ISSUE THREAD

**Issue by 99Kies** [aptos-labs/aptos-core#5277]
fullnode.yaml:
```yaml
base:
    # Update this value to the location you want the node to store its database
    data_dir: ".aptos-full-data"
    role: "full_node"
    waypoint:
        # Update this value to that which the blockchain publicly provides. Please regard the directions
        # below on how to safely manage your genesis_file_location with respect to the waypoint.
        from_file: "./waypoint.txt"

execution:
    # Update this to the location to where the genesis.blob is stored, prefer fullpaths
    # Note, this must be paired with a waypoint. If you update your waypoint without a
    # corresponding genesis, the file location should be an empty path.
    genesis_file_location: "./genesis.blob"

full_node_networks:
    - discovery_method: "onchain"
      # The network must have a listen address to specify protocols. This runs it locally to
      # prevent remote, incoming connections.
      listen_address: "/ip4/127.0.0.1/tcp/6180"
      network_id: "public"
      # Define the upstream peers to connect to
      seeds:
        {}

storage:
    enable_indexer: true
    # This is to avoid the node being pruned
    storage_pruner_config:
        ledger_pruner_config:
            enable: false

indexer:
    enabled: true
    postgres_uri: "postgres://postgres:postgres@localhost:5432/postgres"
    processor: "default_processor"
    check_chain_id: true
    emit_every: 100

api:
    enabled: true
    address: 127.0.0.1:8080
```

start command:
```shell
$ cargo run -p aptos-node --features "indexer" --release -- -f ./fullnode.yaml | grep -E "_processor"
```

bug log:
```
2022-10-25T09:55:03.313873Z [indexer] INFO crates/indexer/src/runtime.rs:248 Processed batch version {"batch_end_version":493499,"batch_start_version":493000,"processor_name":"default_processor","tps":238,"versions_processed":50000}
details = '''panicked at 'Could not fetch 500 transactions after 3 retries, starting at 515000: IO error: While open a file for random read: .aptos-full-data/db/ledger_db/000069.sst: Too many open files', crates/indexer/src/indexer/fetcher.rs:201:21'''
backtrace = '''
   0:        0x10479b8a0 - <unknown>
   1:        0x103098bd0 - <unknown>
   2:        0x1047e9f88 - <unknown>
   3:        0x1047e9e20 - <unknown>
   4:        0x1047e8798 - <unknown>
   5:        0x1047e9b78 - <unknown>
   6:        0x1048c8b44 - <unknown>
   7:        0x1031a5284 - <unknown>
   8:        0x1031c25f4 - <unknown>
   9:        0x1030c5a08 - <unknown>
  10:        0x104770118 - <unknown>
  11:        0x104767ea8 - <unknown>
  12:        0x104767650 - <unknown>
  13:        0x104762714 - <unknown>
  14:        0x104766df8 - <unknown>
  15:        0x10475ec44 - <unknown>
  16:        0x10474f620 - <unknown>
  17:        0x10474d8f8 - <unknown>
  18:        0x104754620 - <unknown>
  19:        0x104756834 - <unknown>
  20:        0x1047ed324 - <unknown>
  21:        0x1a16f826c - <unknown>
'''

details = '''panicked at 'Could not fetch 500 transactions after 3 retries, starting at 514000: IO error: While open a file for random read: .aptos-full-data/db/ledger_db/000069.sst: Too many open files', crates/indexer/src/indexer/fetcher.rs:201:21'''
backtrace = '''
   0:        0x10479b8a0 - <unknown>
   1:        0x103098bd0 - <unknown>
   2:        0x1047e9f88 - <unknown>
   3:        0x1047e9e20 - <unknown>
   4:        0x1047e8798 - <unknown>
   5:        0x1047e9b78 - <unknown>
   6:        0x1048c8b44 - <unknown>
   7:        0x1031a5284 - <unknown>
   8:        0x1031c25f4 - <unknown>
   9:        0x1030c5a08 - <unknown>
  10:        0x104770118 - <unknown>
  11:        0x104767ea8 - <unknown>
  12:        0x104767650 - <unknown>
  13:        0x104762714 - <unknown>
  14:        0x104766df8 - <unknown>
  15:        0x10475ec44 - <unknown>
  16:        0x10474f620 - <unknown>
  17:        0x10474d8f8 - <unknown>
  18:        0x104754620 - <unknown>
  19:        0x104756834 - <unknown>
  20:        0x1047ed324 - <unknown>
  21:        0x1a16f826c - <unknown>
'''

details = '''panicked at 'Could not fetch 500 transactions after 3 retries, starting at 514500: IO error: While open a file for random read: .aptos-full-data/db/ledger_db/000069.sst: Too many open files', crates/indexer/src/indexer/fetcher.rs:201:21'''
backtrace = '''
   0:        0x10479b8a0 - <unknown>
   1:        0x103098bd0 - <unknown>
   2:        0x1047e9f88 - <unknown>
   3:        0x1047e9e20 - <unknown>
   4:        0x1047e8798 - <unknown>
   5:        0x1047e9b78 - <unknown>
   6:        0x1048c8b44 - <unknown>
   7:        0x1031a5284 - <unknown>
   8:        0x1031c25f4 - <unknown>
   9:        0x1030c5a08 - <unknown>
  10:        0x104770118 - <unknown>
  11:        0x104767ea8 - <unknown>
  12:        0x104767650 - <unknown>
  13:        0x104762714 - <unknown>
  14:        0x104766df8 - <unknown>
  15:        0x10475ec44 - <unknown>
  16:        0x10474f620 - <unknown>
  17:        0x10474d8f8 - <unknown>
  18:        0x104754620 - <unknown>
  19:        0x104756834 - <unknown>
  20:        0x1047ed324 - <unknown>
  21:        0x1a16f826c - <unknown>
'''

details = '''panicked at 'Could not fetch 500 transactions after 3 retries, starting at 516000: IO error: While open a file for random read: .aptos-full-data/db/ledger_db/000069.sst: Too many open files', crates/indexer/src/indexer/fetcher.rs:201:21'''
backtrace = '''
   0:        0x10479b8a0 - <unknown>
   1:        0x103098bd0 - <unknown>
   2:        0x1047e9f88 - <unknown>
   3:        0x1047e9e20 - <unknown>
   4:        0x1047e8798 - <unknown>
   5:        0x1047e9b78 - <unknown>
   6:        0x1048c8b44 - <unknown>
   7:        0x1031a5284 - <unknown>
   8:        0x1031c25f4 - <unknown>
   9:        0x1030c5a08 - <unknown>
  10:        0x104770118 - <unknown>
  11:        0x104767ea8 - <unknown>
  12:        0x104767650 - <unknown>
  13:        0x104762714 - <unknown>
  14:        0x104766df8 - <unknown>
  15:        0x10475ec44 - <unknown>
  16:        0x10474f620 - <unknown>
  17:        0x10474d8f8 - <unknown>
  18:        0x104754620 - <unknown>
  19:        0x104756834 - <unknown>
  20:        0x1047ed324 - <unknown>
  21:        0x1a16f826c - <unknown>
'''

details = '''panicked at 'Could not fetch 500 transactions after 3 retries, starting at 515500: IO error: While open a file for random read: .aptos-full-data/db/ledger_db/000069.sst: Too many open files', crates/indexer/src/indexer/fetcher.rs:201:21'''
backtrace = '''
   0:        0x10479b8a0 - <unknown>
   1:        0x103098bd0 - <unknown>
   2:        0x1047e9f88 - <unknown>
   3:        0x1047e9e20 - <unknown>
   4:        0x1047e8798 - <unknown>
   5:        0x1047e9b78 - <unknown>
   6:        0x1048c8b44 - <unknown>
   7:        0x1031a5284 - <unknown>
   8:        0x1031c25f4 - <unknown>
   9:        0x1030c5a08 - <unknown>
  10:        0x104770118 - <unknown>
  11:        0x104767ea8 - <unknown>
  12:        0x104767650 - <unknown>
  13:        0x104762714 - <unknown>
  14:        0x104766df8 - <unknown>
  15:        0x10475ec44 - <unknown>
  16:        0x10474f620 - <unknown>
  17:        0x10474d8f8 - <unknown>
  18:        0x104754620 - <unknown>
  19:        0x104756834 - <unknown>
  20:        0x1047ed324 - <unknown>
  21:        0x1a16f826c - <unknown>
'''
```

<sub>[APT-12](https://linear.app/aptoslabs/issue/APT-12/panicked-at-could-not-fetch-500-transactions-after-3-retries-starting)</sub>
