### ISSUE TITLE
[Bug][Move Prover] `coin::initialize()` causes unconditional abort

### ISSUE THREAD

**Issue by whonore** [aptos-labs/aptos-core#5340]
# 🐛 Bug

Asserting that an address is non-zero followed by calling `coin::initialize()` results in a function that the Move Prover believes aborts unconditionally, which allows anything to be proved. I believe this is because the [spec](https://github.com/aptos-labs/aptos-core/blob/9e7800f46230d10c805129c49cb9ed528a40e25b/aptos-move/framework/aptos-framework/sources/coin.spec.move#L15) for `coin::coin_address()` asserts that it always returns `@0x0`.

## To reproduce

**Code snippet to reproduce**

```move
// sources/test.move
module 0x1234::test {
    use std::string;
    use std::signer;
    use aptos_framework::coin;

    struct TestCoin has key, store {}

    public entry fun init(signer: &signer) {
        assert!(signer::address_of(signer) != @0x0, 0);
    
        // Aborts because signer != @0x0
        let (burn_cap, freeze_cap, mint_cap) =
            coin::initialize<TestCoin>(signer, string::utf8(b"TestCoin"), string::utf8(b"TEST"), 8, true);
        spec { assert false; }; // Succeeds

        coin::destroy_burn_cap(burn_cap);
        coin::destroy_freeze_cap(freeze_cap);
        coin::destroy_mint_cap(mint_cap);
    }

    spec init {
        aborts_if true;
        ensures false;
    }
}
```

```toml
# Move.toml
[package]
name = 'Test'
version = '0.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = '9e7800f46230d10c805129c49cb9ed528a40e25b'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
aptos_framework = "0x1"
```

**Stack trace/error message**
```
$ move prove
[INFO] preparing module 0x1234::test
[INFO] transforming bytecode
[INFO] generating verification conditions
[INFO] 1 verification conditions
[INFO] running solver
[INFO] 0.239s build, 0.177s trafo, 0.003s gen, 0.592s verify, total 1.011s
```

## Expected Behavior

I expect the Prover to fail to prove `false`.

## System information

**Please complete the following information:**
- Aptos commit: 9e7800f46230d10c805129c49cb9ed528a40e25b (mainnet)
- Move commit: move-language/move@ae78e569e44e4e3847cc90f80b20ab4255477e7f
