### ISSUE TITLE
[Bug] Fails to run stake processor indexer

### ISSUE THREAD

**Issue by dbfreem** [aptos-labs/aptos-core#5798]
# 🐛 Bug

When trying to run the Stake indexer I get the below error. 

## To reproduce
Here is the indexer part of the fullnode.yaml

```
indexer:
    enabled: true
    postgres_uri: ********************************
    processor: "stake_processor"
    check_chain_id: true
    emit_every: 500
```

**Stack trace/error message**
```
2022-12-07T10:45:09.406679Z [indexer] ERROR crates/crash-handler/src/lib.rs:39 details = '''panicked at 'Processor unsupported stake_processor', crates/indexer/src/processors/mod.rs:24:18'''
```

## Expected Behavior

The stake_processor to run

## System information

**Build information:**
 build_branch: mainnet
 build_cargo_version: cargo 1.63.0 (fd9c4297c 2022-07-01)
 build_commit_hash: 83f4b2222a81b30a771e0966b55711b0c4caed23
 build_is_release_build: true
 build_os: linux-x86_64
 build_pkg_version: 0.1.0
 build_profile_name: release
 build_rust_channel: 1.63.0-x86_64-unknown-linux-gnu
 build_rust_version: rustc 1.63.0 (4b91a6ea7 2022-08-08)
 build_tag: aptos-node-mainnet_8e9a89829d5c43aa0a092c45b4b26fed7b52b0ca
 build_time: 2022-12-06 02:43:18 +00:00
 build_using_tokio_unstable: true
**Feature information:**
 Running with failpoints feature disabled
 Running with assert-private-keys-not-cloneable feature disabled
