### ISSUE TITLE
[Bug] aptos-sdk = "0.2.7" not working

### ISSUE THREAD

**Issue by gitmalong** [aptos-labs/aptos-core#5993]
Cargo.toml
```toml
[package]
name = "aptostest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aptos-sdk = "0.2.7"
```

`cargo check`
```
aptos % cargo check
    Updating crates.io index
error: no matching package named `aptos-crypto` found
location searched: registry `crates-io`
required by package `aptos-sdk v0.2.7`
    ... which satisfies dependency `aptos-sdk = "^0.2.7"` of package `aptos v0.1.0 
```
