### ISSUE TITLE
[Bug][Aptos Framework] Mainnet/testnet revision compilation is broken

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#8415]
@davidiw 

`Move.toml` for a package:

```toml
[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
```

Results in:

```bash
 % aptos move compile
Compiling, may take a little while to download git dependencies...
UPDATING GIT DEPENDENCY https://github.com/aptos-labs/aptos-core.git
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING Econia
error: provided function signature must match function declaration: type parameter mismatch
  ┌─ /Users/alnoki/.move/https___github_com_aptos-labs_aptos-core_git_mainnet/aptos-move/framework/aptos-framework/../aptos-stdlib/sources/copyable_any.spec.move:7:10
  │
7 │     spec pack<T: drop + store>(x: T): Any {
  │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: provided function signature must match function declaration: type parameter mismatch
  ┌─ /Users/alnoki/.move/https___github_com_aptos-labs_aptos-core_git_mainnet/aptos-move/framework/aptos-framework/sources/object.spec.move:2:10
  │
2 │     spec exists_at<T>(object: address): bool {
  │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

{
  "Error": "Move compilation failed: extended checks failed"
}
```
