### ISSUE TITLE
[Feature Request] Initialize safety-data 

### ISSUE THREAD

**Issue by sherry-x** [aptos-labs/aptos-core#882]
In the validator config, we need to provide safety-rule the secure storage backend for where it can get the safety data. It would be great if we can just provide a list of required private keys / account addresses, and when node started, if safety-data doesn't exist, initialize it itself. 

- In the validator.yaml config file, it should allow us to provide key file path (which includes all the private keys)
- when we specify disk storage backend for safety-rules, it should look for the secure-data file, if that doesn't exist, it should grab all the keys, and create the secure-data file in the data volume (data dir defined in the validator.yaml file too) 

e.g.
```
base:
  role: validator
data_dir: /opt/aptos/data
  waypoint:
    from_file: /opt/aptos/genesis/waypoint.txt

consensus:
  safety_rules:
    service:
      type: "local"
    backend:
      type: on_disk_storage
      path: /opt/aptos/genesis/keys.json
      namespace: ~
```
so for the first time the node bootstrap, safety-rule can read the private keys from `/opt/aptos/genesis/keys.json`, and create a new file on the data_dir `/opt/aptos/data/secure-data.json` with all the data it needs to write
