### ISSUE TITLE
[Bug] peer_id and pubkey mismatch for noise handshake?

### ISSUE THREAD

**Issue by sherry-x** [aptos-labs/aptos-core#891]
I'm having issue connect the validator nodes to each other.
I have two nodes in my genesis, node1 and node2

Node1 with config
```
node1.yml
---
account_address: 7410973313fd0b5c69560fd8cd9c4aaeef873f869d292d1bb94b1872e737d64f
consensus_key: "0x4e6323a4692866d54316f3b08493f161746fda4daaacb6f0a04ec36b6160fdce"
account_key: "0x83f090aee4525052f3b504805c2a0b1d37553d611129289ede2fc9ca5f6aed3c"
network_key: "0xa06381a17b090b8db5ffef97c6e861baad94a1b0e3210e6309de84c15337811d"
validator_host:
  host: abc5b9734d4cc41b99701f9c3c15d7d7-30247cc34f270cb8.elb.us-west-2.amazonaws.com
  port: 6180
full_node_host:
  host: a9c92569fd77341a69cec7bd78008f85-a3666ac007cd2e5f.elb.us-west-2.amazonaws.com
  port: 6182
```

Node2 with:
```
node2.yml
---
account_address: b873bd050a1947bea845b56fbecaa1e0dbd72296c5482bbc7dc57b7a5c537d8e
consensus_key: "0x08fef0ed7f7816fdf1607eb3eba1f5817e8456cbdff63bad5b977d2aa497a59a"
account_key: "0xf2c378809f6ee0ab6941a095ddf6d5f8b5432ed8bbf41f586ffe1d045db88d22"
network_key: "0xd9324a52dba8753a43ada2b6f56552ef678fb0a59b5702a9c2f91c5a4b18ba35"
validator_host:
  host: 35.232.235.105
  port: 6180
full_node_host:
  host: 34.135.169.244
  port: 6182
```

Error logs for node 1
```
2022-05-10T04:27:38.156602Z [network-Validator] ERROR network/src/peer_manager/transport.rs:258 [validator,Validator,
74109733] Outbound connection failed for peer b873bd05 at /ip4/35.232.235.105/tcp/6180/ln-noise-ik/0xd9324a52dba8753a
43ada2b6f56552ef678fb0a59b5702a9c2f91c5a4b18ba35/ln-handshake/0: Transport error: noise client: error reading server
handshake response message, server probably rejected our handshake message: unexpected end of file {"error":"Transport error: noise client: error reading server handshake response message, server probably rejected our handshake messag
e: unexpected end of file","network_address":"/ip4/35.232.235.105/tcp/6180/ln-noise-ik/0xd9324a52dba8753a43ada2b6f56552ef678fb0a59b5702a9c2f91c5a4b18ba35/ln-handshake/0","network_context":{"network_id":"Validator","peer_id":"7410973313fd0b5c69560fd8cd9c4aaeef873f869d292d1bb94b1872e737d64f","role":"validator"},"remote_peer":"B873BD050A1947BEA845B56FBECAA1E0DBD72296C5482BBC7DC57B7A5C537D8E"}
```

Erro logs for node2
```
2022-05-10T05:06:52.451092Z [network-Validator] INFO network/src/connectivity_manager/mod.rs:867 [validator,Validator
,b873bd05] Failed to connect to peer: 74109733 at address: /dns/abc5b9734d4cc41b99701f9c3c15d7d7-30247cc34f270cb8.elb
.us-west-2.amazonaws.com/tcp/6180/ln-noise-ik/0xa06381a17b090b8db5ffef97c6e861baad94a1b0e3210e6309de84c15337811d/ln-h
andshake/0; error: Transport error: noise client: error reading server handshake response message, server probably re
jected our handshake message: unexpected end of file {"error":"Transport error: noise client: error reading server ha
ndshake response message, server probably rejected our handshake message: unexpected end of file","network_address":"
/dns/abc5b9734d4cc41b99701f9c3c15d7d7-30247cc34f270cb8.elb.us-west-2.amazonaws.com/tcp/6180/ln-noise-ik/0xa06381a17b0
90b8db5ffef97c6e861baad94a1b0e3210e6309de84c15337811d/ln-handshake/0","network_context":{"network_id":"Validator","pe
er_id":"b873bd050a1947bea845b56fbecaa1e0dbd72296c5482bbc7dc57b7a5c537d8e","role":"validator"},"remote_peer":"74109733
13FD0B5C69560FD8CD9C4AAEEF873F869D292D1BB94B1872E737D64F"}
```

Endpoint checker result:
```
argo run -p aptos-operational-tool -- check-endpoint --address '/ip4/35.232.235.105/tcp/6180/ln-noise-ik/0xd9324a52dba8753a43ada2b6f56552ef678fb0a59b5702a9c2f91c5a4b18ba35/ln-handshake/0' --chain-id 10 --network-id=Validator --private-key=981922ED778D1732B3511F43D402423EFAE647CF0FC265D1B479E11E72A2E25A
    Finished dev [unoptimized + debuginfo] target(s) in 0.66s
     Running `target/debug/aptos-operational-tool check-endpoint --address /ip4/35.232.235.105/tcp/6180/ln-noise-ik/0xd9324a52dba8753a43ada2b6f56552ef678fb0a59b5702a9c2f91c5a4b18ba35/ln-handshake/0 --chain-id 10 --network-id=Validator --private-key=981922ED778D1732B3511F43D402423EFAE647CF0FC265D1B479E11E72A2E25A`
Connecting with peer_id A06381A17B090B8DB5FFEF97C6E861BAAD94A1B0E3210E6309DE84C15337811D and pubkey a06381a17b090b8db5ffef97c6e861baad94a1b0e3210e6309de84c15337811d to /ip4/35.232.235.105/tcp/6180/ln-noise-ik/0xd9324a52dba8753a43ada2b6f56552ef678fb0a59b5702a9c2f91c5a4b18ba35/ln-handshake/0 with timeout: 5s
{
  "Error": "Unexpected error: Failed to connect to /ip4/35.232.235.105/tcp/6180/ln-noise-ik/0xd9324a52dba8753a43ada2b6f56552ef678fb0a59b5702a9c2f91c5a4b18ba35/ln-handshake/0 due to noise client: error reading server handshake response message, server probably rejected our handshake message: unexpected end of file"
}
```
here I used the private key from node1, but the endpoint check derived peer_id as `A06381A17B090B8DB5FFEF97C6E861BAAD94A1B0E3210E6309DE84C15337811D` instead of `b873bd050a1947bea845b56fbecaa1e0dbd72296c5482bbc7dc57b7a5c537d8e` so maybe there's some mismatch happening here?
